[package]
name = "glace"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
wgpu = "24.0.3"
winit = "0.30.5"
anyhow = "1.0.93"
futures-lite = "2.5.0"
egui = "0.31.1"
egui-wgpu = "0.31.1"
egui-winit = "0.31.1"
# egui = { git = "https://github.com/emilk/egui", rev = "773232b13914b1e4e6e28fcecde80cd163f59bf5" }
# egui-wgpu = { git = "https://github.com/emilk/egui", rev = "773232b13914b1e4e6e28fcecde80cd163f59bf5" }
# egui-winit = { git = "https://github.com/emilk/egui", rev = "773232b13914b1e4e6e28fcecde80cd163f59bf5" }
bytemuck = "1.20.0"

[dependencies.bevy]
version = "0.16.0"
# git = "https://github.com/bevyengine/bevy"
# rev = "5adf831b42a5749aef5ebe91912323083e2ded00"
default-features = false
features = [
  "bevy_asset",
  "bevy_winit",
  "bevy_render",
  "multi_threaded",
  "bevy_window",
  "bevy_log",
]

[features]
trace = []
