[package]
name = "glace"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
wgpu = "26"
winit = "0.30"
anyhow = "1.0"
futures-lite = "2"
# egui = "0.33"
# egui-wgpu = "0.33"
# egui-winit = "0.33"
egui = { git = "https://github.com/emilk/egui", rev = "bd45406fad35992e7b0c53988859ab86f79d5df9" }
egui-wgpu = { git = "https://github.com/emilk/egui", rev = "bd45406fad35992e7b0c53988859ab86f79d5df9" }
egui-winit = { git = "https://github.com/emilk/egui", rev = "bd45406fad35992e7b0c53988859ab86f79d5df9" }
bytemuck = "1.24.0"
gltf = "1.4.1"

[dependencies.bevy]
version = "0.17.3"
# git = "https://github.com/bevyengine/bevy"
# rev = "5adf831b42a5749aef5ebe91912323083e2ded00"
default-features = false
features = [
  "bevy_asset",
  "bevy_winit",
  "bevy_render",
  "multi_threaded",
  "bevy_window",
  "bevy_log",
  "bevy_mesh",
  "debug",
]

[features]
trace = []
