[package]
name = "glace"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[features]
trace = ["bevy/trace"]
trace_tracy = ["trace", "bevy/trace_tracy"]

[dependencies]
wgpu = "29"
winit = "0.30"
anyhow = "1.0"
futures-lite = "2"
egui = "0.35"
egui-wgpu = "0.35"
egui-winit = "0.35"
bytemuck = "1.24.0"
gltf = "1.4.1"

[dependencies.bevy]
version = "0.19.0"
default-features = false
features = [
  "bevy_asset",
  "bevy_winit",
  "bevy_render",
  # "multi_threaded",
  "bevy_window",
  "bevy_log",
  "bevy_mesh",
  "debug",
]
